### ISSUE TITLE
btrfs module

### ISSUE THREAD

**Issue by johnsmitth** [santeri3700/vive-pro-2-on-linux#1]
Build failed due to btrfs kernel module:

> (3/3) Updating linux initcpios...
> ==> Building image from preset: /etc/mkinitcpio.d/linux-vivepro2.preset: 'default'
>   -> -k /boot/vmlinuz-linux-vivepro2 -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-vivepro2.img
> ==> Starting build: 6.0.11-vivepro2-1
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [autodetect]
>   -> Running build hook: [keyboard]
>   -> Running build hook: [keymap]
>   -> Running build hook: [modconf]
>   -> Running build hook: [block]
>   -> Running build hook: [filesystems]
>   -> Running build hook: [fsck]
> **==> ERROR: module not found: btrfs**
> ==> WARNING: No modules were added to the image. This is probably not what you want.
> ==> Creating zstd-compressed initcpio image: /boot/initramfs-linux-vivepro2.img
> ==> WARNING: errors were encountered during the build. The image may not be complete.
> ==> Building image from preset: /etc/mkinitcpio.d/linux-vivepro2.preset: 'fallback'
>   -> -k /boot/vmlinuz-linux-vivepro2 -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-vivepro2-fallback.img -S autodetect
> ==> Starting build: 6.0.11-vivepro2-1
>   -> Running build hook: [base]
>   -> Running build hook: [udev]
>   -> Running build hook: [keyboard]
>   -> Running build hook: [keymap]
>   -> Running build hook: [modconf]
>   -> Running build hook: [block]
>   -> Running build hook: [filesystems]
>   -> Running build hook: [fsck]
> **==> ERROR: module not found: btrfs**
> ==> Generating module dependencies
> ==> Creating zstd-compressed initcpio image: /boot/initramfs-linux-vivepro2-fallback.img
> ==> WARNING: errors were encountered during the build. The image may not be complete.
> **error: command failed to execute correctly**

**Comment by santeri3700** [comment]
I haven't used btrfs, but are your kernel config and mkinitcpio.conf correct? I think I'm able to build the kernel with btrfs module with this.

```
$ grep 'btrfs' /etc/mkinitcpio.conf
MODULES=(btrfs)
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block filesystems fsck btrfs)

$ grep '^CONFIG_BTRFS' ~/.config/linux-vivepro2/myconfig
CONFIG_BTRFS_FS=m
CONFIG_BTRFS_FS_POSIX_ACL=y
```
makepkg -si
```
...
(4/4) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-vivepro2.preset: 'default'
  -> -k /boot/vmlinuz-linux-vivepro2 -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-vivepro2.img
==> Starting build: 6.0.11-vivepro2-1
  -> Running build hook: [base]
...
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
  -> Running build hook: [btrfs]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: /boot/initramfs-linux-vivepro2.img
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux-vivepro2.preset: 'fallback'
  -> -k /boot/vmlinuz-linux-vivepro2 -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-vivepro2-fallback.img -S autodetect
==> Starting build: 6.0.11-vivepro2-1
  -> Running build hook: [base]
...
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
  -> Running build hook: [btrfs]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: /boot/initramfs-linux-vivepro2-fallback.img
==> Image generation successful
```

**Comment by santeri3700** [comment]
I've done a major overhaul to the repository and the kernel is now very close to the official Arch Linux kernel. I'll close this issue assuming that this problem has been resolved now.
