### ISSUE TITLE
Update to 6.5.7

### ISSUE THREAD

**Issue by warmos9** [santeri3700/vive-pro-2-on-linux#3]
Hello, can you update the project to use latest Arch kernel?

I would really like to help with that, but I don't know where to start

**Comment by santeri3700** [comment]
Hi, sorry for the late response! I've done a major overhaul to the repository and updated the kernel to the latest Arch Linux kernel as of writing this (6.7).

I changed the PKGBUILD base to the official one for easier maintenance so most of the time just changing the `pkgver` value should be enough.

Happy VR gaming!
